### ISSUE TITLE
_AD_XUPDATE_LANG_STORE が english/admin.php で定義されていない

### ISSUE THREAD

**Issue by orrisroot** [xoopscube/xupdate#54]
_AD_XUPDATE_LANG_STORE が english/admin.php で定義されていないようです。

Add-on Store »» Module で以下のように出てしまいます。

> required TrustModule _AD_XUPDATE_LANG_STORE:Xoops X (Ten) - GitHub
> Protector is a module to defend your CMS origined from XOOPS2 from various and malicious attacks

**Comment by nao-pon** [comment]
@orrisroot :+1: 
ありがとうございます。修正し、次回 Push 分に含みます。
