### ISSUE TITLE
phpseclib/Math/BigInteger.php compatibility issue with PHP 5.6

### ISSUE THREAD

**Issue by orrisroot** [xoopscube/xupdate#55]
PHP 5.6 環境下で (trust)/modules/xupdate/class/ftp/phpseclib/Math/BigInteger.php がメモリを食い潰すようです。
https://github.com/phpseclib/phpseclib/commit/ad03d8446190a4c34034be50605e7ea829928ffe
が原因で、最新の 1.0 ブランチのコードへアップデートすることで動作するようです。
https://github.com/phpseclib/phpseclib/blob/1.0/phpseclib/Math/BigInteger.php

**Comment by nao-pon** [comment]
@orrisroot お知らせ、ありがとうございます。

現在搭載されているバージョンが何か分からないのですが、現状の最新版は 1.0.2 もしくは 2.0.2 のようですね。いっそのこと、そのどちらか（できれば 2.0.2） にするのが一番良いと思います。

私のメイン環境は FTP 接続の環境ではないのですぐには動作確認が難しく、ご協力願いたいのです。

phpseclib ディレクトリを丸ごと 1.0.2 か 2.0.2 に入れ替えての動作確認はできますでしょうか？

**Comment by orrisroot** [comment]
とりあえず phpseclib 以下を 1.0.2 および 2.0.2 と両方で差し替えてて試してみたところ、どちらもFTP接続で正常に動作しているようです。適当なモジュールを Store から新規インストールして試しています。

packagist 情報では 2.0.2 の方は php: >=5.3.3 のようですので古いPHP切り捨てOKなら 2.0.2 でも良さそうです。

**Comment by nao-pon** [comment]
早速の確認ありがとうございます！ X-update の動作条件が PHP 5.2 以上なので、1.0.2 に取り替えようと思います。

**Comment by nao-pon** [comment]
遅くなりましたが phpseclib 1.0.2 に差し替えて X-update 0.71.2 としました。

Thanks! :+1:

**Comment by orrisroot** [comment]
ありがとうございました。更新を確認できました。
ちなみにこの更新分は PSR-2 化が元に戻った形となってるようですがOKでしたでしょうか。

**Comment by nao-pon** [comment]
ああ、そうでしたね。うっかりしていましたが、ライブラリに関しては、独自に直にカスタマイズをすることはないと思うので、コードスタイルの変更はせずオリジナルのままでよいと思いますが、いかがでしょうか。

**Comment by orrisroot** [comment]
はい。私もそのままでいいと思います。
ありがとうございました。のちほど別件のリクエストをもう一個出しますw
